name: Close Issue
on:
  pull_request:
    types: [closed]
jobs:
  CloseIssue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Close Issue
        run: gh issue close --comment "Auto-closing issue" "$NUMBER"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
