name: Close Issue
on:
  issues:
    types: [opened]
jobs:
  CloseIssue:
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue
        run: gh issue close --comment "Auto-closing issue" "1"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
